# https://hub.docker.com/_/postgres/
# Use postgres/example user/password credentials
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes: 
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # creates initial database schema using SQL file
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080
